apiVersion: v1
kind: ConfigMap
metadata:
  name: spaship-operator-config
  labels:
    spaship: operator
data:
  APP_OPERATOR_ROUTER_MODE: 'ingress'
#  APP_OPERATOR_URL: https://spaship-operator.apps.grey-spoke.dev.iad2.dc.paas.redhat.com
#  APP_OPERATOR_WEBSITE_DOMAIN: 'minikube.info'
#######################
# For Namespace install
# Configured via ENVs
#######################
#  APP_OPERATOR_PROVIDER_ENV_ENABLED: 'true'
#  APP_OPERATOR_PROVIDER_CRD_ENABLED: 'false'
#  WEBSITE_NAMESPACE: 'spaship-examples'
#  WEBSITE_NAME: 'simple'
#  WEBSITE_GITURL: 'https://github.com/spaship/spaship-examples.git'
#  WEBSITE_SSLVERIFY: 'true'                             # Optional
#  WEBSITE_BRANCH: 'main'                                # Optional
#  WEBSITE_CONFIG_DIR: 'websites/02-advanced'            # Optional
#  WEBSITE_WEBHOOK_SECRET: 'CHANGEIT'
